---
title: Anaesthesia meets Vienna
author: Benjamin Gravesteijn
date: '2019-06-04'
slug: euroanesthesia-2019
categories: ["Conference"]
tags: []
---

Mentally, I started preparing for this business trip in Tokyo, Japan. After making my way over to the [national art center](www.nact.jp), I was notified that one of the new exhibitions was "Vienna on her way to Modernism". Through paintings, decorations, and fasion of the fin-de-siècle Viennese art scene, the transformation of Vienna on its way to the 20th century was meticulously displayed. From "just" a European city, to the capitol of the continent, through the development of intensive instrastructure, avant-garde architecture, and of course, the flourishing culture, centered around the Viennese bourgoisie. 

Now, more than a century later, this city is the host of the largest European conference in Anesthesiology: [EuroAnesthesia 2019](http://www.euroanaesthesia2019.com/). Vienna and Europe have come a long way since the 19th century, since this is a completely print-free, technologically driven, huge (>5000 participants) conference. I can imaging that because of this futuristic meeting, participants might forget to also enjoy the classical side of Vienna. However, that sure would not happen to me...

## Vienna

## First impression

## Poster presentation


