---
title: Evolution or revolution
author: Benjamin Gravesteijn
date: '2019-05-24'
slug: evolution-or-revolution
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Yesterday, Daphne Voormolen and I attended a meeting orginized by the main Dutch funding organizations [ZonMW](<https://www.zonmw.nl/nl/>) and the [NWO](<https://www.nwo.nl/>), called ["Evolution or Revolution"](https://www.zonmw.nl/nl/actueel/agenda/detail/item/evolutie-of-revolutie/). The aim of the meeting was to have an open discussion. One where we, as researchers, were asked what they, as funders, could do to help create financial incentives to improve the scientific community. Through panel discussions, break-out sessions, and interactive [menti-questions](https://menti.com), we discussed how the scientific community in 2030 will have to function. The quintessential question was whether the community would go for an evolution, or a revolution in the field.

## Cultural changes
"We are competing and focusing on only such a small fraction of academic work" was commented by someone from the audience at the end of the day. This resonates still with me today. It was commented by a lot of people that competition was necessary in academia, and improves the quality of the work. However, everybody agreed that the cultural systems that are in place rigth now to facilitate competition, are failing.

One of the symptoms of the failing competitive system is the stigma that exists around stepping up and stepping down in academia. [Rianne Letschert](https://twitter.com/Rianneletschert) explained how she was looked down upon when she accepted the honourable position as rector magnificus at Maastricht University. "She must have failed in her academic career", was the comments that she received. While in reality, she took the job just after she received a Veni grant: one of the more prestigious research grants the the [NWO](<https://www.nwo.nl/>). She was able to offer two of her employees a permanent position, so her academic career was -in current terms- definitely succesful. She decided to accept the position as rector maginificus, because she felt that she was neede over there. Both Rianne Letschert as well as [Jet Bussemakers](https://twitter.com/jet_bussemaker) (former minister of science, now professor at the LUMC) proved that our current way of thinking about academic careers is flawed: instead of the 4-tiered ladder (PhD-Postdoc-Associate professor-Professor), a more dynamic, diverse, and personalized career flow should be made possible. 

One of the ways a more dynamic career flow would improve academia is through education. After all, it is one of the three pillars of academia are _creation of knowledge (research)_, _distribution of knowledge (education)_, and _creating impact_ in society. Currently, in terms of rewarding academic work, education is undervalued compared to research. [Jeroen Geurts](https://www.narcis.nl/person/RecordID/PRS1254216/Language/nl), professor a the VU Amsterdam and chairman of ZonMW, explained that he let his employees at the VU decide whether they wanted to focus on education, or on research. This meant that they were recognized by their efforts in their respective profiles. Geurts stated that "strangely enough, the people who had an education profile improved their skills in research too. Similarly, people with a research profile improved their educational skills too." Because the pressure to excell in all fields was no longer present, people could focus on their main abilities. This strengthened their confidence, and let to "collateral improvement". This story inspired me, as well as the audience, and lead to the question how to increase this through financial incentives.  

## Financial incentives
Team science
Education in grant proposal


## The Netherlands and the world
## Rewarding education and impact
## The PhD system
"The PhD system is the source of all evil" was the statements that one of the break-out sessions came up with. Although everybody agreed that this was put too strongly, this statement did spart out the most interactive discussion of the day. A PhD-education is at the doorway to an academic career. By shaping this part of the career, we could improve the future academic culture.

##Conclusion