---
title: 'Research highlight: Cost effectiveness of ECPR'
author: Benjamin Gravesteijn
date: '2019-10-10'
slug: research-highlight-cost-effectiveness-of-ecpr
categories:
  - Research highlight
tags:
  - Anesthesia
  - Publications
---

The first official post in the series of research highlight will be a paper that I recently published in the journal "Resuscitation". The title of the study is ["Cost-effectiveness of extracorporeal cardiopulmonary resuscitation after in-hospital cardiac arrest: A Markov decision model"](https://www.sciencedirect.com/science/article/pii/S0300957219305854?via%3Dihub), which is a lengthy, sophisticated, complex, and incomprehensible title, as research should be. Let's break down what it is about, why we did this study, so we could have a chat about it some time.

# ECPR
This study is about extracorporeal membrane oxygenation (ECMO). This refers to a technique, which is similar to a heart-lung machine: it's a machine which pumps blood around (like a heart), and during that, it allows oxygen to enter the blood and carbon dioxide to leave it (like a lung). This device can take over the function of heart and lungs when the actual organs are too sick to function appropriately. During this period where the function is taken over by the ECMO, they have time to rest and to recover. Therefore, this device is a life saving device, which often is referred to as "cheating death".

This device, ECMO, can 

# Cost effectiveness analysis

# Attention

# Plans 